FROM ubuntu:latest


#RUN apt-get -y install python3-pip
RUN apt update
RUN apt install python3 python3-pip -y
RUN apt-get -y install cron
RUN touch /var/log/cron.log

COPY requirements.txt /requirements.txt
RUN pip3 install --upgrade pip
RUN pip3 install --no-cache-dir -r requirements.txt
COPY main.py ./
#COPY crontab /etc/cron.d/crontab
#RUN chmod 0644 /etc/cron.d/crontab
#RUN touch /var/log/cron.log
#RUN crontab /etc/cron.d/crontab
#RUN (crontab -l ; echo "* * * * * python main.py >> /var/log/cron.log") | crontab
#CMD cron && tail -f /var/log/cron.log

#RUN python3 main.py
ENTRYPOINT [ "python3" ,"./main.py" ]